### ISSUE TITLE
GET /users/<username>/projects/ not listing some projects

### ISSUE THREAD

**Issue by jemole** [LLK/scratch-rest-api#2]
Hi,

I'm testing this method with my username and I see that some of my projects are not listed in the resulting array. For instance, project 46774094 is not listed, but it is an existing project I created:

https://scratch.mit.edu/projects/46774094/

In fact, if I try to get the information of this project (https://api-staging.scratch.mit.edu/users/chenml/projects/46774094), I get a NotFoundError:

{"code":"NotFoundError","message":""}

Best,
Jesús.

**Comment by rschamp** [comment]
The instance at api-staging.scratch.mit.edu uses a separate database from scratch.mit.edu for staging. Please use api.scratch.mit.edu, e.g., https://api.scratch.mit.edu/users/chenml/projects/46774094

**Comment by jemole** [comment]
Thank you!

I used api-staging because is the one indicated in the Scratch Wiki: https://wiki.scratch.mit.edu/wiki/Scratch_API_%282.0%29

Best,
Jesús.
