### ISSUE TITLE
Request for feature to get the projects included in a studio

### ISSUE THREAD

**Issue by jemole** [LLK/scratch-rest-api#3]
Hi, guys!

It would be great if you could include a feature to get the projects that are included in a given studio.

Congratulations for this new API, I think it is going to be really useful. 

Best,
Jesús.

**Comment by rschamp** [comment]
Thank you for the suggestion!  We are building the API as we rebuild parts of the website, so we will definitely add this as soon as we work on studio pages.

**Comment by jemole** [comment]
Wonderful! Than you so much!

**Comment by jemole** [comment]
Hi guys,

Has this feature finally been implemented?

Thanks!

**Comment by rschamp** [comment]
@jemole No, we still have not migrated the studio page.
