### ISSUE TITLE
What is the difference between getting the user's message count via /proxy and via /users?

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-rest-api#5]
These both return the same value:

- https://api.scratch.mit.edu/proxy/users/foo/activity/count
- https://api.scratch.mit.edu/users/foo/messages/count

The latter is used in LLK/scratch-www; I couldn't find /proxy/users/../activity/count being used anywhere in its code.

**Comment by Jonathan50** [comment]
I thought it used the first one and didn't know about the second one... XD Maybe it did use it but they changed it?

**Comment by mewtaylor** [comment]
@towerofnix – @Jonathan50 is correct. The one we use is simply a new route for the same information. The old one will eventually be deprecated but was kept around for a little while during the transition.

Thanks for the nudge as well to update the docs, as we'll be incorporating some new routes in our next release!

**Comment by towerofnix** [comment]
Thanks!

(I'll close this since that's a clear answer.)

**Comment by towerofnix** [comment]
Of note, though - this commit https://github.com/LLK/scratch-www/commit/3dee0e46d2730553f108b4e5e33108aeeeaae60b uses the proxy count rather than the /users/.. count?

**Comment by mewtaylor** [comment]
@towerofnix we ended up changing that back to using `/users/.../count`. The proxy endpoint will eventually disappear, as mentioned above. I'm gonna close this again, but please feel free to re-open if there is another question about this that you have!
