### ISSUE TITLE
statusCode is required

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-rest-api#6]
I am trying to get https://api.scratch.mit.edu/users/kyleplo/projects?limit=80
When I set limit to anything over 40, the following 500 error is returned:
`{"code":"InternalError","message":"statusCode (number) is required"}`

**Comment by mewtaylor** [comment]
@kyleplo we do not allow the limit to be higher than 40, which is what's causing that error

**Comment by towerofnix** [comment]
This issue is also general to other requests that break `limit`'s limit.

**Comment by kyleplo** [comment]
To get, for example, the 41st-80th projects shared, would I use `https://api.scratch.mit.edu/users/kyleplo/projects?limit=40&offset=40`

**Comment by towerofnix** [comment]
@kyleplo Yes, that's the right thing to do. Of course the 81st-120th projects would be ?limit=40&offset=80!

**Comment by kyleplo** [comment]
Thanks! This is for https://github.com/kyleplo/scratch-timeline

**Comment by towerofnix** [comment]
(This is still a bug, though. It should probably be left open, though I imagine it'd probably fit better in the LLK/scratch-api repo, rather than LLK/scratch-rest-api (which is mostly for documentation).)
