### ISSUE TITLE
Why does the "get project" API require the project's author as well as its ID?

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-rest-api#9]
Currently there's only (as far as I know) one endpoint to get a specific project given its ID: [`/users/:username/projects/:project`](https://github.com/LLK/scratch-rest-api/wiki/Projects#get-usersusernameprojectsproject). This endpoint requires both the project's ID and the username of its creator; if the creator does not match, a 404 `NotFound` error is returned.

I'm curious why this endpoint also requires the username? I remember in Scratch 1.4, actual project URLs on the site also included the URL, e.g. https://scratch.mit.edu/projects/_nix/155705899. But in 2.0, that was simplified (and old URLs then redirected) to not include the project creator's username: https://scratch.mit.edu/projects/155705899/

So why does this endpoint require the project's author? (I'll also note there's no `/project/:project` endpoint.) As far as I can tell this makes it more difficult to make a "port" of the 2.0 site; for example, if I give you this URL - `https://scratch.mit.edu/projects/46130596/` - how would I get this project from the API? You don't know who made it, so you can't use the `/users/:username/projects/:project` endpoint!

**Comment by rschamp** [comment]
This is a good question, and we will most likely be addressing this soon!

**Comment by towerofnix** [comment]
Closing this, since there *is* a `/projects/:id` endpoint now!
